# Generated by Django 2.2.10 on 2021-06-05 05:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_name', models.CharField(blank=True, default=django.contrib.auth.models.AbstractUser.get_full_name, max_length=200, verbose_name='Inventory Name')),
                ('Inventory_ID', models.CharField(default='ABCD1234', max_length=8, unique=True, verbose_name='Inventory ID')),
                ('Inventory_followers', models.IntegerField(blank=True, default=0, verbose_name='Inventory Followers')),
                ('Inventory_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
