# Generated by Django 2.2.10 on 2021-06-30 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210629_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 30, 6, 55, 44, 511346), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 30, 6, 55, 44, 509377), null=True, verbose_name='Date of invoice'),
        ),
    ]
