# Generated by Django 2.2.10 on 2021-06-30 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210630_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='Item_stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='After Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_stock',
            field=models.IntegerField(blank=True, default=0, verbose_name='Product Stock'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 30, 6, 58, 10, 80965), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 30, 6, 58, 10, 77557), null=True, verbose_name='Date of invoice'),
        ),
    ]
