# Generated by Django 2.2.10 on 2021-07-01 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210630_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_comments',
            field=models.TextField(blank=True, verbose_name='Invoice Comments'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 1, 3, 42, 27, 592689), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 1, 3, 42, 27, 591520), null=True, verbose_name='Date of invoice'),
        ),
    ]
