# Generated by Django 2.2.10 on 2021-07-22 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210722_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 22, 11, 31, 18, 719372), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 22, 11, 31, 18, 718761), null=True, verbose_name='Date of invoice'),
        ),
    ]
