# Generated by Django 2.2.10 on 2021-08-03 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210723_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Invoice_access_pass',
            field=models.CharField(blank=True, max_length=500, verbose_name='Invoice Access Pass'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 3, 13, 40, 16, 536103), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 3, 13, 40, 16, 535485), null=True, verbose_name='Date of invoice'),
        ),
    ]
