# Generated by Django 2.2.10 on 2021-08-05 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210803_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 11, 41, 41, 109383), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 11, 41, 41, 108778), null=True, verbose_name='Date of invoice'),
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GSTIN_Number', models.CharField(max_length=500, null=True, verbose_name='GSTIN Number')),
                ('PhoneNumber', models.CharField(max_length=500, null=True, verbose_name='Phone Number')),
                ('Email', models.EmailField(max_length=500, null=True, verbose_name='Primary Email')),
                ('Add_line_1', models.CharField(max_length=500, null=True, verbose_name='Address Line 1')),
                ('Add_line_2', models.CharField(max_length=500, null=True, verbose_name='Address Line 2')),
                ('Pin_Code', models.CharField(max_length=500, null=True, verbose_name='Pin Code')),
                ('City', models.CharField(max_length=500, null=True, verbose_name='City')),
                ('State', models.CharField(max_length=500, null=True, verbose_name='State')),
                ('State_Code', models.CharField(max_length=500, null=True, verbose_name='State Code')),
                ('Sales_User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesUser')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_fname', models.CharField(max_length=200, null=True, verbose_name='Customer First Name')),
                ('Customer_lname', models.CharField(max_length=200, null=True, verbose_name='Customer Last Name')),
                ('Customer_phone', models.CharField(max_length=200, null=True, verbose_name='Customer Phone')),
                ('Customer_email', models.CharField(max_length=200, null=True, verbose_name='Customer Email')),
                ('Customer_ID', models.CharField(default='ABCDE12345', max_length=10, unique=True, verbose_name='Sales User ID')),
                ('Customer_GST_no', models.CharField(blank=True, default=' ', max_length=20, verbose_name='GST Number')),
                ('Customer_image', models.ImageField(blank=True, default='sales_user_images/default_sales_user.png', upload_to='Customer_image')),
                ('Customer_Address', models.TextField(blank=True, verbose_name='Address')),
                ('Customer_info', models.TextField(blank=True, verbose_name='Information')),
                ('Sales_User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesUser')),
            ],
        ),
    ]
