# Generated by Django 2.2.10 on 2021-08-05 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210805_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_SKU_Code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Product SKU Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_discount',
            field=models.IntegerField(default=0, verbose_name='Product discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_price_unit',
            field=models.IntegerField(default=0, verbose_name='Product Price Per Unit'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 12, 10, 16, 16628), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 12, 10, 16, 16020), null=True, verbose_name='Date of invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ID',
            field=models.CharField(default='AB1000', max_length=6, verbose_name='Product ID(HSN/SAC Code)'),
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accnt_holder_name', models.CharField(max_length=500, null=True, verbose_name='Account Holder Name')),
                ('Accnt_number', models.CharField(max_length=500, null=True, verbose_name='Account Number')),
                ('Bank_Name', models.CharField(max_length=500, null=True, verbose_name='Bank Name')),
                ('IFSC_Code', models.CharField(max_length=500, null=True, verbose_name='IFSC Code')),
                ('Sales_User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SalesUser')),
            ],
        ),
    ]
