# Generated by Django 2.2.10 on 2021-08-05 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210805_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_type',
            field=models.CharField(choices=[('G', 'Goods'), ('S', 'Services')], default=('G', 'Goods'), max_length=200, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_unit',
            field=models.CharField(choices=[('Each', 'Each'), ('Hour', 'Hour'), ('Item', 'Item'), ('Kg', 'Kilogram'), ('Piece', 'Piece'), ('Set', 'Set')], default=('Each', 'Each'), max_length=200, verbose_name='Product Unit'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 12, 18, 26, 104305), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 5, 12, 18, 26, 103692), null=True, verbose_name='Date of invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ID',
            field=models.CharField(default='P0OMMW', max_length=6, verbose_name='Product ID(HSN/SAC Code)'),
        ),
    ]
