# Generated by Django 2.2.10 on 2021-08-09 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210805_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Invoice_access_pass',
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='Request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 10, 38, 42, 264308), null=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.CharField(default='JGK1D8S6QZ', max_length=10, unique=True, verbose_name='Sales User ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Inventory_ID',
            field=models.CharField(default='ONPZVFS6', max_length=8, unique=True, verbose_name='Inventory ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 10, 38, 42, 263665), null=True, verbose_name='Date of invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_ID',
            field=models.CharField(default='0J5ABJ', max_length=6, verbose_name='Product ID(HSN/SAC Code)'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='SalesUser_ID',
            field=models.CharField(default='U3QLACY3FK', max_length=10, unique=True, verbose_name='Sales User ID'),
        ),
    ]
